### ISSUE TITLE
update default meta image preview to 2.1

### ISSUE THREAD

**Issue by jonesmac** [xylabs/sdk-meta-server-nodejs#220]
See screenshot below when sharing a link from beta.  Still shows 2.0

<img width="461" alt="image" src="https://user-images.githubusercontent.com/885417/230496758-5d6432ad-a384-403b-9b40-d457a8986827.png">

**Comment by JoelBCarter** [comment]
Thanks for posting this @jonesmac.  I did some digging and found that the meta server is just serving up the assets from the head.  The problem is that the images in our `public` folder for our react sites still have images with 2.0 on them.  We'll want to regenerate them.
